name: Build Image

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches:
      - main
      - production
jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out code
        id: checkout
        uses: actions/checkout@v3
      - name: Print message
        run: |
          echo 'Building image...'
          echo context.payload.workflow_run.head_branch
