name: Build Image

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches:
      - main
      - production
jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get branch name
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('BRANCH_NAME', '${{ github.event.workflow_run.head_branch }}');
      # - name: Get branch name
      #   id: get-branch-name
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       return context.payload))
      # - name: Dump context
      #   run: echo '${{ toJSON(github) }}'
      - name: Check out code
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Print message
        run: |
          echo 'Building image...'
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo 'from context: ${{ github.event.workflow_run.head_branch }}'
          echo "from envvar: ${BRANCH_NAME}"
          cat test.txt
      #    echo '${{ context.payload.workflow_run.head_branch }}'
