name: Build Image

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches:
      - main
      - production
jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Print payload
        uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(context.payload))
      - name: Check out code
        id: checkout
        uses: actions/checkout@v3
      - name: Print message
        run: |
          echo 'Building image...'
          env
