name: CI

on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: My job
        run: |
          echo 'Running my job...'
          echo "GITHUB_SHA: ${GITHUB_SHA}"
