name: Print secrets

on:
  workflow_dispatch:
    inputs:
      app_env:
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.app_env }}
    steps:
      - name: Print secrets
        run: |
          echo "APP_ENV: ${{ github.event.inputs.app_env }}"
          echo "REPOSITORY_SECRET"
          case "${{ secrets.REPOSITORY_SECRET }}" in
            "WWW" ) echo '1';;
            "XXX" ) echo '2';;
            "YYY" ) echo '3';;
            "ZZZ" ) echo '4';;
          esac
          echo "DUPLICATED_SECRET"
          case "${{ secrets.DUPLICATED_SECRET }}" in
            "WWW" ) echo '1';;
            "XXX" ) echo '2';;
            "YYY" ) echo '3';;
            "ZZZ" ) echo '4';;
          esac
          echo "ENV_SECRET"
          case "${{ secrets.ENV_SECRET }}" in
            "WWW" ) echo '1';;
            "XXX" ) echo '2';;
            "YYY" ) echo '3';;
            "ZZZ" ) echo '4';;
          esac
