name: Print secrets

on:
  workflow_dispatch:
    inputs:
      app_env:
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.app_env }}
    steps:
      - name: Print secrets
        run: |
          echo "APP_ENV: ${{ github.event.inputs.app_env }}"
          echo "REPOSITORY_SECRET: ${{ secrets.REPOSITORY_SECRET }}" >> test.txt
          echo "DUPLICATED_SECRET: ${{ secrets.DUPLICATED_SECRET }}" >> test.txt
          echo "ENV_SECRET: ${{ secrets.ENV_SECRET }}" >> test.txt
          cat test.txt
